name: Build packages
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build mbzeguard and luci-app-mbzeguard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          VERSION=$(git describe --tags --exact-match 2>/dev/null || echo "dev_$(date +%d%m%Y)")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: mbzeguard:ci
          build-args: |
            PKG_VERSION=${{ steps.version.outputs.version }}

      - name: Create Docker container
        run: docker create --name mbzeguard mbzeguard:ci

      - name: Copy file from Docker container
        run: |
          docker cp mbzeguard:/builder/bin/packages/x86_64/utilites/. ./bin/
          docker cp mbzeguard:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Filter IPK files
        run: |
          # Извлекаем версию из тега, убирая префикс 'v'
          VERSION=${GITHUB_REF#refs/tags/v}

          mkdir -p ./filtered-bin
          cp ./bin/luci-i18n-mbzeguard-ru_*.ipk "./filtered-bin/luci-i18n-mbzeguard-ru_${VERSION}.ipk"
          cp ./bin/mbzeguard_*.ipk ./filtered-bin/
          cp ./bin/luci-app-mbzeguard_*.ipk ./filtered-bin/

      - name: Remove Docker container
        run: docker rm mbzeguard

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./filtered-bin/*.ipk